name: Update Game Manifest

on:
  push:
    paths:
      - '**/*'

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Gather game IDs
        run: |
          # List top-level directories (assuming each game ID is a directory)
          find . -maxdepth 1 -type d ! -path . ! -path ./.github | sed 's|^\./||' \
            | sort > manifest.txt

      - name: Commit and push manifest if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update manifest.txt"
          file_pattern: manifest.txt
          branch: main
